#!/bin/sh

PATH_PART=`dirname $0`
CURRENT_PATH=`pwd`
cd "$PATH_PART"
PATH_PART=`pwd`
cd "$CURRENT_PATH"

PATH_PART=`cygpath -w "$PATH_PART"`

hadoop jar "$PATH_PART\\..\\PCAPCRHadoop\target\\PCAPCRHadoop-1.0-jar-with-dependencies.jar" edu.asu.hadoop.pcapcr.PCAPCRHadoop -conf "$PATH_PART\\hadoop-local.xml" \
21 \
1 \
20 \
0 \
13334 \
6666 \
y \
y \
Threshold-0.90 \
"$PATH_PART\\..\\..\\..\\data\\synthetic-data\\xaa" \
"$PATH_PART\\..\\..\\..\\data\\synthetic-data\\xab" \
"$PATH_PART\\synthetic-pca.data" \
"$PATH_PART\\synthetic-temp" \
"$PATH_PART\\elapsedtime"