#!/bin/sh

# Altai State University, Pavel Nuzhdin, 2011

PATH_PART=`dirname $0`
CURRENT_PATH=`pwd`
cd "$PATH_PART"
PATH_PART=`pwd`
cd "$CURRENT_PATH"

#PATH_PART=`cygpath -w "$PATH_PART"`

hadoop jar "$PATH_PART/../PCAPCRHadoop-1.0-jar-with-dependencies.jar" edu.asu.hadoop.pcapcr.PCAPCRHadoop -conf "$PATH_PART/hadoop-local.xml" \
501 \
1 \
500 \
0 \
666666 \
333334 \
y \
y \
Threshold-0.90 \
"$PATH_PART/../data/synthetic-training" \
"$PATH_PART/../data/synthetic-testing" \
"$PATH_PART/synthetic-pca.data" \
"$PATH_PART/synthetic-temp" \
"$PATH_PART/elapsedtime"