#!/bin/sh

# Altai State University, Pavel Nuzhdin, 2011

PATH_PART=`dirname $0`
CURRENT_PATH=`pwd`
cd "$PATH_PART"
PATH_PART=`pwd`
cd "$CURRENT_PATH"

#PATH_PART=`cygpath -w "$PATH_PART"`

#hdfs dfs -conf "$PATH_PART/hadoop-hetznercluster.xml" -Ddfs.replication=2 -Ddfs.blocksize=102400000 -put \
#     "$PATH_PART/../data/synthetic-training" /pca/synthetic-training

#hdfs dfs -conf "$PATH_PART/hadoop-hetznercluster.xml" -Ddfs.replication=2 -Ddfs.blocksize=102400000 -put \
#     "$PATH_PART/../data/synthetic-testing" /pca/synthetic-testing

hadoop jar "$PATH_PART/../PCAPCRHadoop-1.0-jar-with-dependencies.jar" \
edu.asu.hadoop.pcapcr.PCAPCRHadoop \
-conf "$PATH_PART/hadoop-hetznercluster.xml" \
-Ddfs.replication=2 -Ddfs.blocksize=102400000 \
501 \
1 \
500 \
0 \
666666 \
333334 \
y \
y \
Threshold-0.9 \
/pca/synthetic-training \
/pca/synthetic-testing \
/pca/synthetic-pcadata \
/pca/synthetic-temp \
"$PATH_PART/elapsedtime"